- job:
    name: jjb-tox-linters
    parent: tox
    vars:
      tox_envlist: linters

- job:
    name: jjb-tox-cross-python-jenkins
    description: Tests compatibility with master branch of python-jenkins
    parent: tox-py38
    required-projects:
      - jjb/python-jenkins
      - jjb/jenkins-job-builder
    nodeset: ubuntu-focal
    voting: true

- job:
    name: jjb-tox-docs-linkcheck
    parent: tox
    vars:
      tox_envlist: docs-linkcheck

- project:
    templates:
      - docs-on-readthedocs
      - openstack-python37-jobs-no-constraints
    vars:
      rtd_webhook_id: '47271'
    check:
      jobs:
        - tox-py38:
            nodeset: ubuntu-focal
        - jjb-tox-linters
        - jjb-tox-cross-python-jenkins
        - jjb-tox-docs-linkcheck
        - tox-cover
    gate:
      jobs:
        - tox-py38:
            nodeset: ubuntu-focal
